[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
bytemuck = { version = "1.13.0", features = ["derive"] }
cgmath = "0.18.0"
image = { version = "0.24.5", features = ["png", "jpeg"], default-features = false }
instant = "0.1.12"
pollster = "0.3.0"
tobj = { version = "3.2.4", features = ["async"] }
wgpu = "0.15.1"
winit = "0.28.1"
